[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Environment variables (you'll need to set RESEND_API_KEY in Netlify dashboard)
# RESEND_API_KEY = "your-api-key-here"
